### ISSUE TITLE
Won't let me submit listing

### ISSUE THREAD

**Issue by cahlan** [bdoyle522/bdoyle522.github.io#1]
Wasn't sure if you'd seen this or not:

![bug](http://cl.ly/image/120L0t1k221f/Screen%20Shot%202015-11-30%20at%205.27.47%20PM.png)

**Comment by bdoyle522** [comment]
Do you mean not letting you submit because you didn't select the pets option? If so, I purposely made all of the options required. So that a potential sub-leaser knows whether or not they could sublease with a pet, whether the washer/dryer is community or not, etc.

**Comment by cahlan** [comment]
Ah sorry, I just realized that the first option "Pets" isn't actually an
option.
